<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8464" started-at="2023-05-02T01:40:42 IST" finished-at="2023-05-02T01:40:50 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8464" started-at="2023-05-02T01:40:42 IST" finished-at="2023-05-02T01:40:50 IST">
      <class name="tests.LoginTest">
        <test-method status="PASS" signature="setUpSuite()[pri:0, instance:tests.LoginTest@30cecdca]" name="setUpSuite" is-config="true" duration-ms="39" started-at="2023-05-02T01:40:42 IST" finished-at="2023-05-02T01:40:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method status="PASS" signature="setUpSuperClass(java.lang.String)[pri:0, instance:tests.LoginTest@30cecdca]" name="setUpSuperClass" is-config="true" duration-ms="3715" started-at="2023-05-02T01:40:42 IST" finished-at="2023-05-02T01:40:46 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuperClass -->
        <test-method status="PASS" signature="setUpMethod()[pri:0, instance:tests.LoginTest@30cecdca]" name="setUpMethod" is-config="true" duration-ms="368" started-at="2023-05-02T01:40:47 IST" finished-at="2023-05-02T01:40:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpMethod -->
        <test-method status="SKIP" signature="verifyInValidLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@30cecdca]" name="verifyInValidLogin" duration-ms="387" retried="true" started-at="2023-05-02T01:40:47 IST" data-provider="getInvalidLoginData" finished-at="2023-05-02T01:40:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[InvalidUser1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pages.LoginPage.login(LoginPage.java:39)
at tests.LoginTest.verifyInValidLogin(LoginTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInValidLogin -->
        <test-method status="PASS" signature="setUpMethod()[pri:0, instance:tests.LoginTest@30cecdca]" name="setUpMethod" is-config="true" duration-ms="62" started-at="2023-05-02T01:40:48 IST" finished-at="2023-05-02T01:40:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpMethod -->
        <test-method status="FAIL" signature="verifyInValidLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@30cecdca]" name="verifyInValidLogin" duration-ms="285" started-at="2023-05-02T01:40:48 IST" data-provider="getInvalidLoginData" finished-at="2023-05-02T01:40:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[InvalidUser1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pages.LoginPage.login(LoginPage.java:39)
at tests.LoginTest.verifyInValidLogin(LoginTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInValidLogin -->
        <test-method status="PASS" signature="setUpMethod()[pri:0, instance:tests.LoginTest@30cecdca]" name="setUpMethod" is-config="true" duration-ms="40" started-at="2023-05-02T01:40:48 IST" finished-at="2023-05-02T01:40:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpMethod -->
        <test-method status="PASS" signature="verifyValidLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@30cecdca]" name="verifyValidLogin" duration-ms="305" started-at="2023-05-02T01:40:48 IST" data-provider="getValidLoginData" finished-at="2023-05-02T01:40:49 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyValidLogin -->
        <test-method status="PASS" signature="setUpMethod()[pri:0, instance:tests.LoginTest@30cecdca]" name="setUpMethod" is-config="true" duration-ms="49" started-at="2023-05-02T01:40:49 IST" finished-at="2023-05-02T01:40:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpMethod -->
        <test-method status="PASS" signature="verifyValidLoginLogout(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@30cecdca]" name="verifyValidLoginLogout" duration-ms="976" started-at="2023-05-02T01:40:49 IST" data-provider="getValidLoginData" finished-at="2023-05-02T01:40:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyValidLoginLogout -->
        <test-method status="PASS" signature="tearDownSuperClass()[pri:0, instance:tests.LoginTest@30cecdca]" name="tearDownSuperClass" is-config="true" duration-ms="653" started-at="2023-05-02T01:40:50 IST" finished-at="2023-05-02T01:40:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuperClass -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
